version: '3'

tasks:
  default:
    desc: Run tests
    cmds:
      - task: test

  test:
    desc: Run unit tests (no Docker required)
    cmds:
      - go test -short -v ./...

  test:all:
    desc: Run all tests including integration tests (requires Docker)
    cmds:
      - go test -v ./... -timeout 30m

  test:bench:
    desc: "Run benchmarks. Examples: task bench, task bench FILTER=Upload, task bench FILTER=LocalHash (no Docker)"
    vars:
      FILTER: '{{.FILTER | default "."}}'
      COUNT: '{{.COUNT | default "1"}}'
    cmds:
      - go test -bench={{.FILTER}} -benchmem -count={{.COUNT}} ./... -timeout 30m

  test:fuzz:
    desc: "Run fuzz tests. Example: task fuzz TARGET=FuzzExpandPath TIME=30s"
    vars:
      TARGET: '{{.TARGET | default "FuzzExpandPath"}}'
      TIME: '{{.TIME | default "30s"}}'
    cmds:
      - go test -fuzz={{.TARGET}} -fuzztime={{.TIME}} ./...


  test:coverage:
    desc: Generate coverage report (requires Docker)
    cmds:
      - go test -tags=integration -coverprofile=./.out/coverage.out -covermode=atomic ./...
      - go tool cover -html=./.out/coverage.out -o coverage.html
      - go tool cover -func=./.out/coverage.out | grep total | awk '{print "Total coverage:", $3}'

  lint:
    desc: Run golangci-lint
    cmds:
      - golangci-lint run ./...

  fmt:
    desc: Format code
    cmds:
      - go fmt ./...
